version: '3'
services:
  directus:
    image: directus/directus:latest
    volumes:
      - ./uploads:/directus/uploads
      - ./database:/directus/database
    env_file:
      - .env
    ports:
      - 8055:8055